version: '3.9'

services:
  # Сервис для разворачивания контейнера с базой данных
  database:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=DripChip
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Enter5510


  # Сервис для разворачивания контейнера с приложением
  webapi:
    image: drip-chip:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - server.port=8080
      - spring.datasource.url=jdbc:postgresql://database:5432/DripChip
      - spring.datasource.username=postgres
      - spring.datasource.password=Enter5510
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.jpa.hibernate.ddl-auto=create-drop


  # Сервис для разворачивания контейнера с автотестами
  tests:
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - webapi
    environment:
      SERVER_URL: http://webapi:8080
      STAGE: all
      # all - запуск всех тестов из трёх доступных этапов
      # 0, 1 или 2 - запуск тестов для соответствующего этапа
